-- Create tables from gtw_schema.json

CREATE TABLE IF NOT EXISTS gtw.vehicle (
    vin VARCHAR(17) NOT NULL PRIMARY KEY, 
    active BOOLEAN DEFAULT true NOT NULL, 
    creation_date TIMESTAMP(6) NOT NULL, 
    update_date TIMESTAMP(6) NOT NULL, 
    vehicle_architecture VARCHAR(7) NOT NULL, 
    vehicle_program_code VARCHAR(3), 
    vehicle_region VARCHAR(5)
);

CREATE TABLE IF NOT EXISTS gtw.ecu (
    serial_number VARCHAR(25) NOT NULL PRIMARY KEY, 
    active BOOLEAN DEFAULT true NOT NULL, 
    device_type VARCHAR(10) NOT NULL, 
    device_variant_type VARCHAR(50), 
    vin VARCHAR(17) NOT NULL REFERENCES gtw.vehicle, 
    creation_date TIMESTAMP(6) DEFAULT CURRENT_TIMESTAMP NOT NULL, 
    update_date TIMESTAMP(6) DEFAULT CURRENT_TIMESTAMP NOT NULL
);

CREATE TABLE IF NOT EXISTS gtw.registration_events (
    event_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, 
    binding_mode VARCHAR(255), 
    life_time INTEGER, 
    location_path VARCHAR(19) UNIQUE, 
    lwm2m_version VARCHAR(5), 
    registration_date TIMESTAMP(6), 
    registration_update_date TIMESTAMP(6), 
    status VARCHAR(28), 
    serial_number VARCHAR(25) UNIQUE REFERENCES gtw.ecu
);

CREATE TABLE IF NOT EXISTS gtw.device_operations_group_reference (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, 
    created_date TIMESTAMP(6) NOT NULL, 
    expiration_date TIMESTAMP(6), 
    group_id VARCHAR(36) NOT NULL UNIQUE, 
    priority VARCHAR(8), 
    serial_number VARCHAR(25) NOT NULL, 
    status VARCHAR(11) NOT NULL CHECK (status IN ('IN_PROGRESS','CLOSED','QUEUED')), 
    updated_date TIMESTAMP(6) NOT NULL
);

CREATE TABLE IF NOT EXISTS gtw.device_operation_reference (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, 
    cache_operation_object JSONB, 
    group_id VARCHAR(36) NOT NULL, 
    object_id INTEGER NOT NULL, 
    object_name VARCHAR(80), 
    object_version VARCHAR(255), 
    operation_id VARCHAR(36) NOT NULL, 
    operation_type VARCHAR(15), 
    redis_stream_id VARCHAR(36) NOT NULL, 
    status VARCHAR(12) NOT NULL CHECK (status IN ('EXPIRED','QUEUED','SUCCESS','FAILED','TERMINATED')), 
    uri VARCHAR(30) NOT NULL, 
    operation_group_id BIGINT REFERENCES gtw.device_operations_group_reference, 
    creation_date TIMESTAMP(6) DEFAULT CURRENT_TIMESTAMP NOT NULL, 
    update_date TIMESTAMP(6) DEFAULT CURRENT_TIMESTAMP NOT NULL
);

CREATE TABLE IF NOT EXISTS gtw.object_definition (
    object_id INTEGER NOT NULL, 
    version VARCHAR(7) NOT NULL, 
    active BOOLEAN DEFAULT true NOT NULL, 
    creation_date TIMESTAMP(6) NOT NULL, 
    instance VARCHAR(255) NOT NULL, 
    object_template JSONB, 
    update_date TIMESTAMP(6) NOT NULL, 
    urn VARCHAR(32), 
    PRIMARY KEY (object_id, version)
);

CREATE TABLE IF NOT EXISTS gtw.instance_definition (
    internal_instance_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, 
    active BOOLEAN DEFAULT true NOT NULL, 
    creation_date TIMESTAMP(6) NOT NULL, 
    desc_overwritten VARCHAR(255), 
    instance_id INTEGER, 
    name_overwritten VARCHAR(255), 
    resource_instance_definition JSONB, 
    update_date TIMESTAMP(6) NOT NULL, 
    object_id INTEGER, 
    version VARCHAR(7), 
    FOREIGN KEY (object_id, version) REFERENCES gtw.object_definition
);
