-- ensure schema exists
CREATE SCHEMA IF NOT EXISTS gtw AUTHORIZATION postgres;

-- =======================
-- Sequences
-- =======================
CREATE SEQUENCE gtw.batch_step_execution_seq;
ALTER SEQUENCE gtw.batch_step_execution_seq OWNER TO postgres;

CREATE SEQUENCE gtw.batch_job_execution_seq;
ALTER SEQUENCE gtw.batch_job_execution_seq OWNER TO postgres;

CREATE SEQUENCE gtw.batch_job_seq;
ALTER SEQUENCE gtw.batch_job_seq OWNER TO postgres;

-- =======================
-- Table: event
-- =======================
CREATE TABLE gtw.event
(
    event_id                 SERIAL PRIMARY KEY,
    binding_mode             VARCHAR(3),
    device_object_status     JSONB,
    life_time                INTEGER,
    lwm2m_version            VARCHAR(5),
    registration_date        TIMESTAMP(6) NOT NULL,
    registration_id          VARCHAR(255) NOT NULL,
    registration_update_date TIMESTAMP(6) NOT NULL,
    status                   VARCHAR(25),
    serial_number            VARCHAR(19)
);
ALTER TABLE gtw.event OWNER TO postgres;

-- =======================
-- Batch Job / Step Tables
-- =======================
CREATE TABLE gtw.batch_job_instance
(
    job_instance_id BIGINT NOT NULL PRIMARY KEY,
    version         BIGINT,
    job_name        VARCHAR(100) NOT NULL,
    job_key         VARCHAR(32)  NOT NULL
);
ALTER TABLE gtw.batch_job_instance OWNER TO postgres;

CREATE TABLE gtw.batch_job_execution
(
    job_execution_id BIGINT NOT NULL PRIMARY KEY,
    version          BIGINT,
    job_instance_id  BIGINT NOT NULL
        REFERENCES gtw.batch_job_instance,
    create_time      TIMESTAMP NOT NULL,
    start_time       TIMESTAMP,
    end_time         TIMESTAMP,
    status           VARCHAR(10),
    exit_code        VARCHAR(20),
    exit_message     VARCHAR(2500),
    last_updated     TIMESTAMP
);
ALTER TABLE gtw.batch_job_execution OWNER TO postgres;

CREATE TABLE gtw.batch_job_execution_params
(
    job_execution_id BIGINT NOT NULL
        REFERENCES gtw.batch_job_execution,
    parameter_name   VARCHAR(100) NOT NULL,
    parameter_type   VARCHAR(100) NOT NULL,
    parameter_value  VARCHAR(2500),
    identifying      CHAR NOT NULL
);
ALTER TABLE gtw.batch_job_execution_params OWNER TO postgres;

CREATE TABLE gtw.batch_step_execution
(
    step_execution_id  BIGINT NOT NULL PRIMARY KEY,
    version            BIGINT NOT NULL,
    step_name          VARCHAR(100) NOT NULL,
    job_execution_id   BIGINT NOT NULL
        REFERENCES gtw.batch_job_execution,
    create_time        TIMESTAMP NOT NULL,
    start_time         TIMESTAMP,
    end_time           TIMESTAMP,
    status             VARCHAR(10),
    commit_count       BIGINT,
    read_count         BIGINT,
    filter_count       BIGINT,
    write_count        BIGINT,
    read_skip_count    BIGINT,
    write_skip_count   BIGINT,
    process_skip_count BIGINT,
    rollback_count     BIGINT,
    exit_code          VARCHAR(20),
    exit_message       VARCHAR(2500),
    last_updated       TIMESTAMP
);
ALTER TABLE gtw.batch_step_execution OWNER TO postgres;

CREATE TABLE gtw.batch_job_execution_context
(
    job_execution_id   BIGINT NOT NULL PRIMARY KEY
        REFERENCES gtw.batch_job_execution,
    short_context      VARCHAR(2500) NOT NULL,
    serialized_context VARCHAR(2500)
);
ALTER TABLE gtw.batch_job_execution_context OWNER TO postgres;

CREATE TABLE gtw.batch_step_execution_context
(
    step_execution_id  BIGINT NOT NULL PRIMARY KEY
        REFERENCES gtw.batch_step_execution,
    short_context      VARCHAR(2500) NOT NULL,
    serialized_context VARCHAR(2500)
);
ALTER TABLE gtw.batch_step_execution_context OWNER TO postgres;

-- =======================
-- Domain Tables
-- =======================
CREATE TABLE gtw.vehicle
(
    vin                  VARCHAR(17)          NOT NULL PRIMARY KEY,
    active               BOOLEAN DEFAULT true NOT NULL,
    creation_date        TIMESTAMP(6)         NOT NULL,
    update_date          TIMESTAMP(6)         NOT NULL,
    vehicle_architecture VARCHAR(7)           NOT NULL,
    vehicle_program_code VARCHAR(3),
    vehicle_region       VARCHAR(5)
);
ALTER TABLE gtw.vehicle OWNER TO postgres;

CREATE TABLE gtw.ecu
(
    serial_number       VARCHAR(25) NOT NULL PRIMARY KEY,
    active              BOOLEAN DEFAULT true NOT NULL,
    device_type         VARCHAR(10) NOT NULL,
    device_variant_type VARCHAR(50),
    vin                 VARCHAR(17) NOT NULL REFERENCES gtw.vehicle,
    creation_date       TIMESTAMP(6) DEFAULT CURRENT_TIMESTAMP NOT NULL,
    update_date         TIMESTAMP(6) DEFAULT CURRENT_TIMESTAMP NOT NULL
);
ALTER TABLE gtw.ecu OWNER TO postgres;

CREATE TABLE gtw.registration_events
(
    event_id                 INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    binding_mode             VARCHAR(255),
    life_time                INTEGER,
    location_path            VARCHAR(19) UNIQUE,
    lwm2m_version            VARCHAR(5),
    registration_date        TIMESTAMP(6),
    registration_update_date TIMESTAMP(6),
    status                   VARCHAR(28),
    serial_number            VARCHAR(25) UNIQUE REFERENCES gtw.ecu
);
ALTER TABLE gtw.registration_events OWNER TO postgres;

CREATE TABLE gtw.registration_object_status_events
(
    ecu_object_instance_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    object_attributes      JSONB,
    object_url             VARCHAR(8),
    event_id               INTEGER NOT NULL REFERENCES gtw.registration_events,
    creation_date          TIMESTAMP(6) DEFAULT CURRENT_TIMESTAMP NOT NULL,
    update_date            TIMESTAMP(6) DEFAULT CURRENT_TIMESTAMP NOT NULL
);
ALTER TABLE gtw.registration_object_status_events OWNER TO postgres;

-- =======================
-- Operation Tables
-- =======================
CREATE TABLE gtw.device_operations_group_reference
(
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_date    TIMESTAMP(6) NOT NULL,
    expiration_date TIMESTAMP(6),
    group_id        VARCHAR(36) NOT NULL UNIQUE,
    priority        VARCHAR(8),
    serial_number   VARCHAR(25) NOT NULL,
    status          VARCHAR(11) NOT NULL
        CHECK (status IN ('IN_PROGRESS','CLOSED','QUEUED')),
    updated_date    TIMESTAMP(6) NOT NULL
);
ALTER TABLE gtw.device_operations_group_reference OWNER TO postgres;

CREATE TABLE gtw.device_operation_reference
(
    id                     BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cache_operation_object JSONB,
    group_id               VARCHAR(36) NOT NULL,
    object_id              INTEGER NOT NULL,
    object_name            VARCHAR(80),
    object_version         VARCHAR(255),
    operation_id           VARCHAR(36) NOT NULL,
    operation_type         VARCHAR(15),
    redis_stream_id        VARCHAR(36) NOT NULL,
    status                 VARCHAR(12) NOT NULL
        CHECK (status IN ('EXPIRED','QUEUED','SUCCESS','FAILED','TERMINATED')),
    uri                    VARCHAR(30) NOT NULL,
    operation_group_id     BIGINT REFERENCES gtw.device_operations_group_reference,
    creation_date          TIMESTAMP(6) DEFAULT CURRENT_TIMESTAMP NOT NULL,
    update_date            TIMESTAMP(6) DEFAULT CURRENT_TIMESTAMP NOT NULL
);
ALTER TABLE gtw.device_operation_reference OWNER TO postgres;

-- =======================
-- Object / Instance Definitions
-- =======================
CREATE TABLE gtw.object_definition
(
    object_id       INTEGER NOT NULL,
    version         VARCHAR(7) NOT NULL,
    active          BOOLEAN DEFAULT true NOT NULL,
    creation_date   TIMESTAMP(6) NOT NULL,
    instance        VARCHAR(255) NOT NULL,
    object_template JSONB,
    update_date     TIMESTAMP(6) NOT NULL,
    urn             VARCHAR(32),
    PRIMARY KEY (object_id, version)
);
ALTER TABLE gtw.object_definition OWNER TO postgres;

CREATE TABLE gtw.device_type_object_reference
(
    id            INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    active        BOOLEAN DEFAULT true NOT NULL,
    device_type   VARCHAR(10) NOT NULL,
    object_id     INTEGER,
    version       VARCHAR(7),
    creation_date TIMESTAMP(6) DEFAULT CURRENT_TIMESTAMP NOT NULL,
    update_date   TIMESTAMP(6) DEFAULT CURRENT_TIMESTAMP NOT NULL,
    FOREIGN KEY (object_id, version) REFERENCES gtw.object_definition
);
ALTER TABLE gtw.device_type_object_reference OWNER TO postgres;
CREATE INDEX idx_device_type_object_reference_device_type_active
    ON gtw.device_type_object_reference (device_type, active);

CREATE TABLE gtw.instance_definition
(
    internal_instance_id         INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    active                       BOOLEAN DEFAULT true NOT NULL,
    creation_date                TIMESTAMP(6) NOT NULL,
    desc_overwritten             VARCHAR(255),
    instance_id                  INTEGER,
    name_overwritten             VARCHAR(255),
    resource_instance_definition JSONB,
    update_date                  TIMESTAMP(6) NOT NULL,
    object_id                    INTEGER,
    version                      VARCHAR(7),
    FOREIGN KEY (object_id, version) REFERENCES gtw.object_definition
);
ALTER TABLE gtw.instance_definition OWNER TO postgres;

CREATE TABLE gtw.device_type_instance_reference
(
    id                   INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    active               BOOLEAN DEFAULT true NOT NULL,
    device_type          VARCHAR(10),
    internal_instance_id INTEGER REFERENCES gtw.instance_definition,
    creation_date        TIMESTAMP(6) DEFAULT CURRENT_TIMESTAMP NOT NULL,
    update_date          TIMESTAMP(6) DEFAULT CURRENT_TIMESTAMP NOT NULL
);
ALTER TABLE gtw.device_type_instance_reference OWNER TO postgres;
CREATE INDEX idx_instance_definition_instance_id_active
    ON gtw.instance_definition (instance_id, active);

CREATE INDEX idx_object_definition_objectid_version_active
    ON gtw.object_definition (object_id, version, active);

-- =======================
-- Vector storage
-- =======================
CREATE TABLE gtw.chunks
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    content    TEXT NOT NULL,
    created_at TIMESTAMP(6) NOT NULL,
    embedding  VECTOR(1536) NOT NULL
);
ALTER TABLE gtw.chunks OWNER TO postgres;

CREATE TABLE gtw.knowledge_chunks
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    content    TEXT NOT NULL,
    created_at TIMESTAMP(6) NOT NULL,
    embedding  VECTOR(1536) NOT NULL
);
ALTER TABLE gtw.knowledge_chunks OWNER TO postgres;

-- =======================
-- Materialized Views
-- =======================
CREATE MATERIALIZED VIEW gtw.gtw_instance_definition_view AS
SELECT id.internal_instance_id,
       id.instance_id,
       id.object_id,
       id.version,
       (resource.value ->> 'resourceId')::INTEGER AS resource_id,
        id.active
FROM gtw.instance_definition id,
     LATERAL jsonb_array_elements(id.resource_instance_definition) resource(value);
ALTER MATERIALIZED VIEW gtw.gtw_instance_definition_view OWNER TO postgres;

CREATE MATERIALIZED VIEW gtw.gtw_object_definition_view AS
SELECT od.object_id,
       od.version,
       (resource.value ->> 'resourceId')::INTEGER   AS resource_id,
        resource.value ->> 'operations'              AS operation,
    resource.value ->> 'type'                    AS type,
    resource.value ->> 'resourceMandatory'       AS resource_mandatory,
    od.object_template ->> 'instances'           AS instances,
    od.active
FROM gtw.object_definition od,
    LATERAL jsonb_array_elements(od.object_template -> 'resources') resource(value);
ALTER MATERIALIZED VIEW gtw.gtw_object_definition_view OWNER TO postgres;
