package com.stellantis.lwm2m.mcp.server.service;

import java.util.List;
import java.util.Map;

/**
 * Database service abstraction for: 1) Retrieving relevant schema embeddings from pgvector based on
 * a user prompt. 2) Generating SQL from an LLM using the prompt + retrieved context. 3) Executing
 * SQL and returning tabular results.
 */
public interface DatabaseService {

  /**
   * Executes an SQL statement (typically generated by {@link #}) and returns the tabular result.
   *
   * @param sql SQL statement to execute
   * @return list of rows as key-value pairs
   */
  List<Map<String, Object>> executeGeneratedSql(String sql);
}
